const actionTypes = {
  PRODUCTS_FETCHING: "PRODUCTS_FETCHING",
  PRODUCTS_FETCHING_SUCCESS: "PRODUCTS_FETCHING_SUCCESS",
  PRODUCTS_FETCHING_ERROR: "PRODUCTS_FETCHING_ERROR",

  // CART ITEM ACTIONS
  CARTITEMS_FETCHING: "CARTITEMS_FETCHING",
  CARTITEMS_FETCHING_SUCCESS: "CARTITEMS_FETCHING_SUCCESS",
  CARTITEMS_FETCHING_ERROR: "CARTITEMS_FETCHING_ERROR",
};

export default actionTypes;
